version: "3"
services:
  omeroextrator:
    image: "ghcr.io/mat-o-lab/omeroextractor:latest"
    container_name: "omeroextrator"
    environment:
      APP_MODE: "production"
      ADMIN_MAIL: ${ADMIN_MAIL}
      OMERO_WEB_HOST: "http://omeroweb:4080"
      OMERO_WEB_USER: ${OMERO_WEB_PUBLIC_USER}
      OMERO_WEB_PASS: ${OMERO_WEB_PUBLIC_PASSWORD}
    ports:
      - ${APP_PORT}:5000
    restart: always
    networks:
      - omero
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/api/info"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 20

networks:
  omero:
    name: omero_net
